<div id="corner-img"><img src="/images/site-images/bird.png" class="" /></div>
<section id="contact-main-content">
    <article id="contact-body-copy">
        <h4>Contact me by email or Facebook! <br /> I check my messages very frequently</h4>
    </article>
    <?php echo $this->form; ?>
    <div class="clearfix-20"></div>
    <section id="like-me-on-facebook">
        <h4>Like me on Facebook:<span class="fb-text">facebook.com/sunnyrosephotography</span></h4>
        <a href="http://www.facebook.com/sunnyrosephotography"><img src="/images/site-images/contact/fb.png" alt="fb link" /></a>
    </section>
</section>